# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7a73a25853c69de5bed5064263e3efe23c1bc0dd3b8643612602c1b84376292f3801ec2c45dcf5fae8316e98e6840357c5a7c325278e6cd4a471e683831402

test:
  secret_key_base: f4a44b065751fbba87c8c8d73fd8de91bf080986ab2afa7e96181e8782f61ea6ba211e85dc030abe7dea9c413a4a3c2ec2aa31d5fc350ff41ab2631930f9adfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
